import React, { useEffect, useState, useCallback } from 'react';
import { Box, Typography, TextField, Button, IconButton, Paper, Dialog, DialogTitle, DialogContent, DialogContentText, DialogActions, FormControl, InputLabel, Select, MenuItem, Switch, FormControlLabel, Alert, CircularProgress, TableContainer, Table, TableHead, TableBody, TableRow, TableCell, Chip, useMediaQuery, useTheme } from '@mui/material';
import AddIcon from '@mui/icons-material/Add'; import EditIcon from '@mui/icons-material/Edit'; import DeleteIcon from '@mui/icons-material/Delete'; import RestoreIcon from '@mui/icons-material/Restore'; import HistoryIcon from '@mui/icons-material/History'; import FolderIcon from '@mui/icons-material/Folder'; import ListAltIcon from '@mui/icons-material/ListAlt'; import DeleteSweepIcon from '@mui/icons-material/DeleteSweep'; import ReceiptLongIcon from '@mui/icons-material/ReceiptLong';
import { getGroups, createGroup, updateGroup, deleteGroup, getProjects, createProject, updateProject, deleteProject, getRecords, restoreRecord, getAuditLogs } from '../api/client';
import type { ProjectGroup, Project, WorkRecord, AuditLog } from '../types';
type TV = 'groups' | 'projects' | 'trash' | 'audit';
const R = '2px';
const AL: Record<string, string> = { create: '创建', delete: '删除', restore: '恢复', update: '修改' };
const AC: Record<string, 'success' | 'error' | 'info' | 'warning'> = { create: 'success', delete: 'error', restore: 'info', update: 'warning' };
const TL: Record<string, string> = { work_records: '工作量记录', project_groups: '分组', projects: '项目' };
const TC = [{ key: 'groups', label: '分组管理', icon: <FolderIcon />, desc: '创建和编辑实验室分组' },{ key: 'projects', label: '项目管理', icon: <ListAltIcon />, desc: '管理分组下的项目' },{ key: 'trash', label: '回收站', icon: <DeleteSweepIcon />, desc: '恢复已删除的记录' },{ key: 'audit', label: '审计日志', icon: <ReceiptLongIcon />, desc: '操作记录追溯' }] as { key: TV; label: string; icon: React.ReactNode; desc: string }[];
const cSx = { borderRadius: R, background: 'linear-gradient(145deg, #ffffff, #f5f5f5)', border: '1px solid rgba(0,0,0,0.06)', boxShadow: '0 4px 20px rgba(0,0,0,0.06)' };
const lSx = { p: 2, borderRadius: R, mb: 1, background: 'linear-gradient(145deg, #ffffff, #fafafa)', border: '1px solid rgba(0,0,0,0.05)' };
const tSx = { borderRadius: R, background: 'linear-gradient(145deg, #ffffff, #fafafa)', border: '1px solid rgba(0,0,0,0.05)', boxShadow: '0 2px 16px rgba(0,0,0,0.04)' };

const ManagePage: React.FC = () => {
  const th = useTheme(); const im = useMediaQuery(th.breakpoints.down('sm'));
  const [tb, setTb] = useState<TV>('groups'); const [ld, setLd] = useState(false); const [er, setEr] = useState(''); const [sc, setSc] = useState('');
  const [gs, setGs] = useState<ProjectGroup[]>([]); const [gdo, setGdo] = useState(false); const [gf, setGf] = useState({ id: 0, name: '', sort_order: 0 }); const [ged, setGed] = useState(false);
  const [ps, setPs] = useState<Project[]>([]); const [sg, setSg] = useState(0); const [pdo, setPdo] = useState(false); const [pf, setPf] = useState({ id: 0, name: '', full_name: '', notes: '', group_id: 0, sort_order: 0, is_active: 1 }); const [ped, setPed] = useState(false);
  const [tr, setTr] = useState<WorkRecord[]>([]); const [al, setAl] = useState<AuditLog[]>([]); const [ap, setAp] = useState(1); const [at, setAt] = useState(0);
  const [co, setCo] = useState(false); const [ca, setCa] = useState<() => void>(() => {});

  const lg = useCallback(async () => { try { const r = await getGroups(); if (r.code === 0) setGs(r.data as ProjectGroup[]); } catch {} }, []);
  const lp = useCallback(async () => { try { const r = await getProjects(); if (r.code === 0) setPs(r.data as Project[]); } catch {} }, []);
  const lt = useCallback(async () => { try { const r = await getRecords({ include_deleted: true, page_size: 200 }); if (r.code === 0) { const d = r.data as { items: WorkRecord[] }; setTr((d.items || []).filter(x => x.deleted_at !== null)); } } catch {} }, []);
  const la = useCallback(async (pg = 1) => { try { const r = await getAuditLogs({ page: pg, page_size: 50 }); if (r.code === 0) { const d = r.data as { items: AuditLog[]; total: number }; setAl(d.items || []); setAt(d.total || 0); setAp(pg); } } catch {} }, []);
  useEffect(() => { setLd(true); Promise.all([lg(), lp(), lt()]).finally(() => setLd(false)); }, [lg, lp, lt]);
  useEffect(() => { if (tb === 'audit') la(1); }, [tb, la]);
  const sm = (m: string, isErr = false) => { if (isErr) { setEr(m); setTimeout(() => setEr(''), 3000); } else { setSc(m); setTimeout(() => setSc(''), 3000); } };

  return (<Box>
    <Typography variant="h5" fontWeight={700} sx={{ mb: 3, px: 1, background: 'linear-gradient(135deg, #f4511e, #e53935)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>管理</Typography>
    {er && <Alert severity="error" sx={{ mx: 1, mb: 2, borderRadius: R }}>{er}</Alert>}
    {sc && <Alert severity="success" sx={{ mx: 1, mb: 2, borderRadius: R }}>{sc}</Alert>}
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2,1fr)', sm: 'repeat(4,1fr)' }, gap: 1.5, mb: 3, px: 1 }}>{TC.map(c => { const ia = tb === c.key; return <Paper key={c.key} elevation={0} onClick={() => setTb(c.key)} sx={{ ...cSx, p: im ? 1.5 : 2, cursor: 'pointer', textAlign: 'center', borderColor: ia ? '#f4511e60' : 'rgba(0,0,0,0.06)', background: ia ? 'linear-gradient(145deg,#fff5f3,#ffebee)' : undefined, '&:hover': { transform: 'translateY(-3px)', boxShadow: '0 8px 30px rgba(244,81,30,0.12)' } }}><Box sx={{ display: 'flex', justifyContent: 'center', mb: 0.8, color: ia ? '#f4511e' : '#888' }}>{c.icon}</Box><Typography variant={im ? 'body2' : 'subtitle2'} fontWeight={ia ? 700 : 500} color={ia ? '#f4511e' : 'text.primary'}>{c.label}</Typography>{!im && <Typography variant="caption" color="text.secondary">{c.desc}</Typography>}</Paper> })}</Box>
    <Box sx={{ px: 1 }}>
      {tb === 'groups' && <Box><Box sx={{ display: 'flex', justifyContent: 'flex-end', mb: 2 }}><Button variant="contained" startIcon={<AddIcon />} onClick={() => { setGf({ id: 0, name: '', sort_order: 0 }); setGed(false); setGdo(true); }} sx={{ borderRadius: R, background: 'linear-gradient(135deg,#f4511e,#e53935)', boxShadow: '0 4px 14px rgba(244,81,30,0.3)' }}>新建分组</Button></Box>{gs.length === 0 ? <Typography color="text.secondary" textAlign="center" sx={{ py: 4 }}>暂无分组</Typography> : gs.map(g => <Paper key={g.id} elevation={0} sx={lSx}><Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><Box><Typography variant="subtitle1" fontWeight={600}>{g.name}</Typography><Typography variant="caption" color="text.secondary">{g.project_count} 个项目 · 排序: {g.sort_order}</Typography></Box><Box sx={{ display: 'flex', gap: 0.5 }}><IconButton onClick={() => { setGf({ id: g.id, name: g.name, sort_order: g.sort_order }); setGed(true); setGdo(true); }} size="small" sx={{ color: '#f4511e' }}><EditIcon fontSize="small" /></IconButton><IconButton onClick={() => { setCa(() => async () => { const r = await deleteGroup(g.id); if (r.code === 0) { sm('删除成功'); lg(); } else sm(r.message, true); setCo(false); }); setCo(true); }} size="small" color="error"><DeleteIcon fontSize="small" /></IconButton></Box></Box></Paper>)}</Box>}
      {tb === 'projects' && <Box><Box sx={{ display: 'flex', gap: 1, mb: 2, flexWrap: 'wrap', justifyContent: 'space-between' }}><FormControl size="small" sx={{ minWidth: 150 }}><InputLabel>选择分组</InputLabel><Select value={sg} label="选择分组" onChange={e => setSg(Number(e.target.value))} sx={{ borderRadius: R }}><MenuItem value={0}>全部分组</MenuItem>{gs.map(g => <MenuItem key={g.id} value={g.id}>{g.name}</MenuItem>)}</Select></FormControl><Button variant="contained" startIcon={<AddIcon />} onClick={() => { if (!sg) { sm('请先选择分组', true); return; } setPf({ id: 0, name: '', full_name: '', notes: '', group_id: sg, sort_order: 0, is_active: 1 }); setPed(false); setPdo(true); }} sx={{ borderRadius: R, background: 'linear-gradient(135deg,#f4511e,#e53935)', boxShadow: '0 4px 14px rgba(244,81,30,0.3)' }}>新建项目</Button></Box>{(ps.filter(p => !sg || p.group_id === sg).length === 0) ? <Typography color="text.secondary" textAlign="center" sx={{ py: 4 }}>暂无项目</Typography> : ps.filter(p => !sg || p.group_id === sg).map(p => <Paper key={p.id} elevation={0} sx={lSx}><Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><Box><Typography variant="subtitle1" fontWeight={600}>{p.name}</Typography><Typography variant="caption" color="text.secondary">分组: {p.group_name} · {p.is_active ? <Chip label="启用" size="small" color="success" sx={{ borderRadius: R, height: 20, fontSize: '0.7rem' }} /> : <Chip label="已停用" size="small" color="default" sx={{ borderRadius: R, height: 20, fontSize: '0.7rem' }} />} · 排序: {p.sort_order}</Typography></Box><Box sx={{ display: 'flex', gap: 0.5 }}><IconButton onClick={() => { setPf({ id: p.id, name: p.name, full_name: p.full_name || '', notes: p.notes || '', group_id: p.group_id, sort_order: p.sort_order, is_active: p.is_active }); setPed(true); setPdo(true); }} size="small" sx={{ color: '#f4511e' }}><EditIcon fontSize="small" /></IconButton><IconButton onClick={() => { setCa(() => async () => { const r = await deleteProject(p.id); if (r.code === 0) { sm('删除成功'); lp(); } else sm(r.message, true); setCo(false); }); setCo(true); }} size="small" color="error"><DeleteIcon fontSize="small" /></IconButton></Box></Box></Paper>)}</Box>}
      {tb === 'trash' && <Box><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>共 {tr.length} 条已删除记录</Typography>{tr.length === 0 ? <Typography color="text.secondary" textAlign="center" sx={{ py: 4 }}>回收站为空</Typography> : <TableContainer component={Paper} className="table-responsive" sx={tSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>项目</TableCell><TableCell sx={{ fontWeight: 600 }}>用户</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>数量</TableCell><TableCell sx={{ fontWeight: 600 }}>删除时间</TableCell><TableCell sx={{ fontWeight: 600 }}>操作</TableCell></TableRow></TableHead><TableBody>{tr.map(r => <TableRow key={r.id} hover><TableCell>{r.project_name || r.group_name}</TableCell><TableCell>{r.user_name}</TableCell><TableCell align="right">{r.quantity}</TableCell><TableCell>{r.deleted_at}</TableCell><TableCell><Button size="small" startIcon={<RestoreIcon />} onClick={async () => { const r2 = await restoreRecord(r.id); if (r2.code === 0) { sm('恢复成功'); lt(); } else sm(r2.message, true); }} sx={{ borderRadius: R, color: '#f4511e' }}>恢复</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>}</Box>}
      {tb === 'audit' && <Box><Typography variant="body2" color="text.secondary" sx={{ mb: 2, display: 'flex', alignItems: 'center', gap: 1 }}><HistoryIcon fontSize="small" />共 {at} 条操作记录</Typography>{al.length === 0 ? <Typography color="text.secondary" textAlign="center" sx={{ py: 4 }}>暂无审计日志</Typography> : <><TableContainer component={Paper} className="table-responsive" sx={tSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>时间</TableCell><TableCell sx={{ fontWeight: 600 }}>操作类型</TableCell><TableCell sx={{ fontWeight: 600 }}>操作对象</TableCell><TableCell sx={{ fontWeight: 600 }}>记录ID</TableCell><TableCell sx={{ fontWeight: 600 }}>操作人</TableCell></TableRow></TableHead><TableBody>{al.map(l => <TableRow key={l.id} hover><TableCell sx={{ whiteSpace: 'nowrap' }}>{l.created_at}</TableCell><TableCell><Chip label={AL[l.action] || l.action} size="small" color={AC[l.action] || 'default'} variant="outlined" sx={{ borderRadius: R }} /></TableCell><TableCell>{TL[l.table_name] || l.table_name}</TableCell><TableCell>{l.record_id}</TableCell><TableCell>{l.user_name}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Box sx={{ display: 'flex', justifyContent: 'center', mt: 2, gap: 1 }}><Button size="small" disabled={ap <= 1} onClick={() => la(ap - 1)} sx={{ borderRadius: R }}>上一页</Button><Typography variant="body2">{ap} / {Math.max(1, Math.ceil(at / 50))}</Typography><Button size="small" disabled={ap * 50 >= at} onClick={() => la(ap + 1)} sx={{ borderRadius: R }}>下一页</Button></Box></>}</Box>}
    </Box>
    <Dialog open={gdo} onClose={() => setGdo(false)} maxWidth="sm" fullWidth PaperProps={{ sx: { borderRadius: R } }}><DialogTitle sx={{ fontWeight: 700 }}>{ged ? '编辑分组' : '新建分组'}</DialogTitle><DialogContent><TextField autoFocus label="分组名称" fullWidth value={gf.name} onChange={e => setGf({ ...gf, name: e.target.value })} sx={{ mt: 1, '& .MuiOutlinedInput-root': { borderRadius: R } }} /><TextField label="排序" type="number" fullWidth value={gf.sort_order} onChange={e => setGf({ ...gf, sort_order: Number(e.target.value) })} sx={{ mt: 2, '& .MuiOutlinedInput-root': { borderRadius: R } }} /></DialogContent><DialogActions><Button onClick={() => setGdo(false)} sx={{ borderRadius: R }}>取消</Button><Button onClick={async () => { if (!gf.name.trim()) { sm('请输入分组名称', true); return; } if (ged) { const r = await updateGroup(gf.id, { name: gf.name, sort_order: gf.sort_order }); if (r.code === 0) { sm('更新成功'); lg(); setGdo(false); } else sm(r.message, true); } else { const r = await createGroup({ name: gf.name, sort_order: gf.sort_order }); if (r.code === 0) { sm('创建成功'); lg(); setGdo(false); } else sm(r.message, true); } }} variant="contained" sx={{ borderRadius: R }}>保存</Button></DialogActions></Dialog>
    <Dialog open={pdo} onClose={() => setPdo(false)} maxWidth="sm" fullWidth PaperProps={{ sx: { borderRadius: R } }}><DialogTitle sx={{ fontWeight: 700 }}>{ped ? '编辑项目' : '新建项目'}</DialogTitle><DialogContent>{!ped && <FormControl fullWidth sx={{ mt: 1 }}><InputLabel>所属分组</InputLabel><Select value={pf.group_id} label="所属分组" onChange={e => setPf({ ...pf, group_id: Number(e.target.value) })} sx={{ borderRadius: R }}>{gs.map(g => <MenuItem key={g.id} value={g.id}>{g.name}</MenuItem>)}</Select></FormControl>}<TextField label="项目名称" fullWidth value={pf.name} onChange={e => setPf({ ...pf, name: e.target.value })} sx={{ mt: 2, '& .MuiOutlinedInput-root': { borderRadius: R } }} /><TextField label="全称" fullWidth value={pf.full_name} onChange={e => setPf({ ...pf, full_name: e.target.value })} sx={{ mt: 2, '& .MuiOutlinedInput-root': { borderRadius: R } }} /><TextField label="备注" fullWidth multiline minRows={2} maxRows={4} value={pf.notes} onChange={e => setPf({ ...pf, notes: e.target.value })} sx={{ mt: 2, '& .MuiOutlinedInput-root': { borderRadius: R } }} /><TextField label="排序" type="number" fullWidth value={pf.sort_order} onChange={e => setPf({ ...pf, sort_order: Number(e.target.value) })} sx={{ mt: 2, '& .MuiOutlinedInput-root': { borderRadius: R } }} />{ped && <FormControlLabel control={<Switch checked={pf.is_active === 1} onChange={e => setPf({ ...pf, is_active: e.target.checked ? 1 : 0 })} />} label="启用" sx={{ mt: 1 }} />}</DialogContent><DialogActions><Button onClick={() => setPdo(false)} sx={{ borderRadius: R }}>取消</Button><Button onClick={async () => { if (!pf.name.trim()) { sm('请输入项目名称', true); return; } if (ped) { const r = await updateProject(pf.id, { name: pf.name, full_name: pf.full_name, notes: pf.notes, sort_order: pf.sort_order, is_active: pf.is_active }); if (r.code === 0) { sm('更新成功'); lp(); setPdo(false); } else sm(r.message, true); } else { const r = await createProject({ group_id: pf.group_id, name: pf.name, sort_order: pf.sort_order }); if (r.code === 0) { sm('创建成功'); lp(); setPdo(false); } else sm(r.message, true); } }} variant="contained" sx={{ borderRadius: R }}>保存</Button></DialogActions></Dialog>
    <Dialog open={co} onClose={() => setCo(false)} PaperProps={{ sx: { borderRadius: R } }}><DialogTitle sx={{ fontWeight: 700 }}>确认操作</DialogTitle><DialogContent><DialogContentText>确定要执行此操作吗？此操作不可撤销。</DialogContentText></DialogContent><DialogActions><Button onClick={() => setCo(false)} sx={{ borderRadius: R }}>取消</Button><Button onClick={ca} color="error" variant="contained" sx={{ borderRadius: R }}>确认</Button></DialogActions></Dialog>
  </Box>);
};
export default ManagePage;
