import React, { useEffect, useState, useCallback } from 'react';
import {
  Box, Typography, Table, TableBody, TableCell, TableContainer,
  TableHead, TableRow, Paper, Button, CircularProgress, Alert,
  FormControl, InputLabel, Select, MenuItem, Chip,
  useMediaQuery, useTheme, IconButton, Dialog, DialogTitle,
  DialogContent, DialogActions, TextField, Grid,
} from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import EditIcon from '@mui/icons-material/Edit';
import DeleteForeverIcon from '@mui/icons-material/DeleteForever';
import ViewWeekIcon from '@mui/icons-material/ViewWeek';
import CalendarMonthIcon from '@mui/icons-material/CalendarMonth';
import PeopleIcon from '@mui/icons-material/People';
import FolderIcon from '@mui/icons-material/Folder';
import ScienceIcon from '@mui/icons-material/Science';
import PrecisionManufacturingIcon from '@mui/icons-material/PrecisionManufacturing';
import HistoryIcon from '@mui/icons-material/History';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import dayjs from 'dayjs';
import isoWeek from 'dayjs/plugin/isoWeek';
import StatsCards from '../components/StatsCards';
import DateRangePicker from '../components/DateRangePicker';
import ConfirmDialog from '../components/ConfirmDialog';
import { getStatsSummary, getStatsByUser, getStatsByProject, getStatsByType, getStatsByInstrument, exportExcel, getGroups, getRecords, updateRecord, deleteRecordsByUser } from '../api/client';
import type { StatsSummary, UserStats, ProjectStats, TypeStats, InstrumentStats, ProjectGroup, StatsDetail, WorkRecord } from '../types';

dayjs.extend(isoWeek);
export type TabValue = 'week' | 'month' | 'user' | 'project' | 'type' | 'instrument' | 'user-log';
interface StatCardDef { key: TabValue; label: string; icon: React.ReactNode; color: string; desc: string; }

const R = '2px';
const cardSx = { p: 2.5, borderRadius: R, cursor: 'pointer', background: 'linear-gradient(145deg, #ffffff, #f5f5f5)', border: '1px solid rgba(0,0,0,0.06)', boxShadow: '0 4px 20px rgba(0,0,0,0.06)', transition: 'all 0.3s cubic-bezier(0.4,0,0.2,1)', '&:hover': { transform: 'translateY(-4px)', boxShadow: '0 8px 30px rgba(0,0,0,0.1)' } };
const STAT_CARDS: StatCardDef[] = [{ key: 'week', label: '按周统计', icon: <ViewWeekIcon />, color: '#667eea', desc: '每月第几周汇总' },{ key: 'month', label: '按月统计', icon: <CalendarMonthIcon />, color: '#43a047', desc: '每月汇总数据' },{ key: 'user', label: '按用户', icon: <PeopleIcon />, color: '#f57c00', desc: '每人工作量' },{ key: 'project', label: '按项目', icon: <FolderIcon />, color: '#7b1fa2', desc: '各项目汇总' },{ key: 'type', label: '按类型', icon: <ScienceIcon />, color: '#0097a7', desc: '液相/气相分类' },{ key: 'instrument', label: '按仪器', icon: <PrecisionManufacturingIcon />, color: '#d32f2f', desc: '各仪器汇总' },{ key: 'user-log', label: '用户日志', icon: <HistoryIcon />, color: '#5d4037', desc: '逐条记录明细' }];
const tablePaperSx = { borderRadius: R, background: 'linear-gradient(145deg, #ffffff, #fafafa)', border: '1px solid rgba(0,0,0,0.05)', boxShadow: '0 2px 16px rgba(0,0,0,0.04)' };
const chipSx = { bgcolor: 'rgba(102,126,234,0.1)', color: '#667eea', fontWeight: 600, borderRadius: R };

const StatsPage: React.FC = () => {
  const t = useTheme(); const m = useMediaQuery(t.breakpoints.down('sm'));
  const [ac, setAc] = useState<TabValue | null>(null); const [s, setS] = useState(() => dayjs().startOf('isoWeek').format('YYYY-MM-DD')); const [e, setE] = useState(() => dayjs().endOf('isoWeek').format('YYYY-MM-DD'));
  const [ld, setLd] = useState(false); const [er, setEr] = useState(''); const [sm, setSm] = useState<StatsSummary | null>(null);
  const [us, setUs] = useState<UserStats[]>([]); const [ps, setPs] = useState<ProjectStats[]>([]); const [ts, setTs] = useState<TypeStats[]>([]); const [is, setIs] = useState<InstrumentStats[]>([]);
  const [dt, setDt] = useState<StatsDetail[]>([]); const [gs, setGs] = useState<ProjectGroup[]>([]); const [gf, setGf] = useState(0);
  const [ul, setUl] = useState<WorkRecord[]>([]); const [ull, setUll] = useState(false); const [ulp, setUlp] = useState(1); const [ult, setUlt] = useState(0); const [uf, setUf] = useState(''); const PS = 100;
  const [edo, setEdo] = useState(false); const [ef, setEf] = useState({ id: 0, user_name: '', quantity: 0, recorded_at: '' }); const [ee, setEe] = useState('');
  const [duo, setDuo] = useState(false); const [dun, setDun] = useState(''); const [dul, setDul] = useState(false);

  const lg = async () => { try { const r = await getGroups(); if (r.code === 0) setGs(r.data as ProjectGroup[]); } catch {} };
  useEffect(() => { lg(); }, []);
  const si = dayjs(s).format('YYYY-MM-DDTHH:mm:ss'); const ei = dayjs(e).endOf('day').format('YYYY-MM-DDTHH:mm:ss');
  const lul = useCallback(async (pg = 1) => { setUll(true); try { const p: any = { start: si, end: ei, page: pg, page_size: PS }; if (uf) p.user_name = uf; const r = await getRecords(p); if (r.code === 0) { const d = r.data as { items: WorkRecord[]; total: number }; setUl(d.items || []); setUlt(d.total || 0); setUlp(pg); } } catch {} finally { setUll(false); } }, [si, ei, uf]);
  const ld2 = useCallback(async () => { if (!ac) return; setLd(true); setEr(''); try { if (ac === 'week' || ac === 'month') { const r = await getStatsSummary({ start: si, end: ei, group_by: ac === 'week' ? 'week' : 'month' }); if (r.code === 0) { setSm(r.data as StatsSummary); setDt((r.data as any).details || []); } else setEr(r.message); } else if (ac === 'user') { const r = await getStatsByUser({ start: si, end: ei }); if (r.code === 0) setUs(r.data as UserStats[]); else setEr(r.message); } else if (ac === 'project') { const r = await getStatsByProject({ start: si, end: ei, group_id: gf || undefined }); if (r.code === 0) setPs(r.data as ProjectStats[]); else setEr(r.message); } else if (ac === 'type') { const r = await getStatsByType({ start: si, end: ei }); if (r.code === 0) setTs(r.data as TypeStats[]); else setEr(r.message); } else if (ac === 'instrument') { const r = await getStatsByInstrument({ start: si, end: ei }); if (r.code === 0) setIs(r.data as InstrumentStats[]); else setEr(r.message); } else if (ac === 'user-log') await lul(1); } catch { setEr('加载失败'); } finally { setLd(false); } }, [ac, si, ei, gf]);
  useEffect(() => { ld2(); }, [ld2]);
  useEffect(() => { (async () => { try { const r = await getStatsSummary({ start: si, end: ei, group_by: 'week' }); if (r.code === 0) setSm(r.data as StatsSummary); } catch {} })(); }, [si, ei]);
  const hx = async () => { try { const b = await exportExcel({ start: si, end: ei, group_id: gf || undefined }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = `工作量统计_${s}_${e}.xlsx`; a.click(); URL.revokeObjectURL(u); } catch { setEr('导出失败'); } };
  const oed = (r: WorkRecord) => { setEf({ id: r.id, user_name: r.user_name, quantity: r.quantity, recorded_at: dayjs(r.recorded_at).format('YYYY-MM-DDTHH:mm') }); setEe(''); setEdo(true); };
  const hes = async () => { if (!ef.user_name.trim()) { setEe('请输入用户名'); return; } if (ef.quantity < 1) { setEe('数量必须大于0'); return; } try { const r = await updateRecord(ef.id, { user_name: ef.user_name, quantity: ef.quantity, recorded_at: dayjs(ef.recorded_at).format('YYYY-MM-DDTHH:mm:ss') }); if (r.code === 0) { setEdo(false); lul(ulp); } else setEe(r.message); } catch { setEe('保存失败'); } };
  const odu = (n: string) => { setDun(n); setDuo(true); };
  const hdu = async () => { setDul(true); try { const r = await deleteRecordsByUser(dun, { start: si, end: ei }); if (r.code === 0) { setDuo(false); lul(ulp); const r2 = await getStatsSummary({ start: si, end: ei, group_by: 'week' }); if (r2.code === 0) setSm(r2.data as StatsSummary); } else { setEr(r.message); setDuo(false); } } catch { setEr('删除失败'); setDuo(false); } finally { setDul(false); } };

  const cg = () => (<Grid container spacing={2}>{STAT_CARDS.map((c) => (<Grid item xs={12} sm={6} md={4} key={c.key}><Paper onClick={() => { setAc(c.key); setEr(''); }} sx={{ ...cardSx, '&:hover': { ...cardSx['&:hover'], borderColor: `${c.color}50`, boxShadow: `0 12px 30px ${c.color}20` } }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}><Box sx={{ width: 40, height: 40, borderRadius: R, display: 'flex', alignItems: 'center', justifyContent: 'center', bgcolor: `${c.color}16`, color: c.color }}>{c.icon}</Box><Typography variant="subtitle1" fontWeight={700}>{c.label}</Typography></Box><Typography variant="body2" color="text.secondary">{c.desc}</Typography></Paper></Grid>))}</Grid>);

  const cct = () => { if (!ac) return null; return (<Box><Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}><IconButton onClick={() => { setAc(null); setEr(''); }} size="small" sx={{ bgcolor: 'rgba(0,0,0,0.04)', borderRadius: R }}><ArrowBackIcon /></IconButton><Typography variant="h6" fontWeight={700}>{STAT_CARDS.find(x => x.key === ac)?.label ?? ''}</Typography></Box>{ac === 'project' && (<Box sx={{ mb: 2 }}><FormControl size="small" sx={{ minWidth: 150 }}><InputLabel>分组筛选</InputLabel><Select value={gf} label="分组筛选" onChange={x => setGf(Number(x.target.value))} sx={{ borderRadius: R }}><MenuItem value={0}>全部分组</MenuItem>{gs.map(g => (<MenuItem key={g.id} value={g.id}>{g.name}</MenuItem>))}</Select></FormControl></Box>)}{er && <Alert severity="error" sx={{ mb: 2, borderRadius: R }}>{er}</Alert>}{ld ? <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}><CircularProgress /></Box> : <Box>
  {(ac === 'week' || ac === 'month') && (<TableContainer component={Paper} className="table-responsive" sx={tablePaperSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>时间</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>总数量</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>记录数</TableCell></TableRow></TableHead><TableBody>{dt.length === 0 ? <TableRow><TableCell colSpan={3} align="center">暂无数据</TableCell></TableRow> : dt.map((d, i) => (<TableRow key={i} hover><TableCell>{d.period}</TableCell><TableCell align="right"><Chip label={d.total_quantity} size="small" sx={chipSx} /></TableCell><TableCell align="right">{d.record_count}</TableCell></TableRow>))}</TableBody></Table></TableContainer>)}
  {ac === 'user' && (<TableContainer component={Paper} className="table-responsive" sx={tablePaperSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>用户名</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>总数量</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>记录数</TableCell></TableRow></TableHead><TableBody>{us.length === 0 ? <TableRow><TableCell colSpan={3} align="center">暂无数据</TableCell></TableRow> : us.map((u, i) => (<TableRow key={i} hover><TableCell>{u.user_name}</TableCell><TableCell align="right"><Chip label={u.total_quantity} size="small" sx={chipSx} /></TableCell><TableCell align="right">{u.record_count}</TableCell></TableRow>))}</TableBody></Table></TableContainer>)}
  {ac === 'project' && (<TableContainer component={Paper} className="table-responsive" sx={tablePaperSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>分组</TableCell><TableCell sx={{ fontWeight: 600 }}>项目</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>总数量</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>记录数</TableCell></TableRow></TableHead><TableBody>{ps.length === 0 ? <TableRow><TableCell colSpan={4} align="center">暂无数据</TableCell></TableRow> : ps.map((p) => (<TableRow key={p.project_id} hover><TableCell>{p.group_name}</TableCell><TableCell>{p.project_name}</TableCell><TableCell align="right"><Chip label={p.total_quantity} size="small" sx={chipSx} /></TableCell><TableCell align="right">{p.record_count}</TableCell></TableRow>))}</TableBody></Table></TableContainer>)}
  {ac === 'type' && (<TableContainer component={Paper} className="table-responsive" sx={tablePaperSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>类型</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>总数量</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>记录数</TableCell></TableRow></TableHead><TableBody>{ts.length === 0 ? <TableRow><TableCell colSpan={3} align="center">暂无数据</TableCell></TableRow> : ts.map((x, i) => (<TableRow key={i} hover><TableCell><Chip label={x.instrument_type} size="small" color={x.instrument_type === '液相' ? 'info' : x.instrument_type === '气相' ? 'success' : 'default'} sx={{ borderRadius: R }} /></TableCell><TableCell align="right"><Chip label={x.total_quantity} size="small" sx={chipSx} /></TableCell><TableCell align="right">{x.record_count}</TableCell></TableRow>))}</TableBody></Table></TableContainer>)}
  {ac === 'instrument' && (<TableContainer component={Paper} className="table-responsive" sx={tablePaperSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>仪器</TableCell><TableCell sx={{ fontWeight: 600 }}>类型</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>总数量</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>记录数</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>用户数</TableCell></TableRow></TableHead><TableBody>{is.length === 0 ? <TableRow><TableCell colSpan={5} align="center">暂无数据</TableCell></TableRow> : is.map((x, i) => (<TableRow key={i} hover><TableCell><Chip label={x.instrument} size="small" color={x.instrument_type === '液相' ? 'info' : 'success'} sx={{ borderRadius: R }} /></TableCell><TableCell><Chip label={x.instrument_type} size="small" color={x.instrument_type === '液相' ? 'info' : 'success'} variant="outlined" sx={{ borderRadius: R }} /></TableCell><TableCell align="right"><Chip label={x.total_quantity} size="small" sx={chipSx} /></TableCell><TableCell align="right">{x.record_count}</TableCell><TableCell align="right">{x.user_count}</TableCell></TableRow>))}</TableBody></Table></TableContainer>)}
  {ac === 'user-log' && (<Box><Box sx={{ mb: 2, display: 'flex', gap: 2, alignItems: 'center', flexWrap: 'wrap' }}><FormControl size="small" sx={{ minWidth: 150 }}><InputLabel>筛选用户</InputLabel><Select value={uf} label="筛选用户" onChange={x => { setUf(x.target.value); setUlp(1); }} sx={{ borderRadius: R }}><MenuItem value="">全部用户</MenuItem>{[...new Set(ul.map(r => r.user_name))].map(n => <MenuItem key={n} value={n}>{n}</MenuItem>)}</Select></FormControl><Typography variant="body2" color="text.secondary">共 {ult} 条</Typography></Box>{ull ? <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}><CircularProgress /></Box> : <><TableContainer component={Paper} className="table-responsive" sx={tablePaperSx}><Table size="small"><TableHead><TableRow><TableCell sx={{ fontWeight: 600 }}>序号</TableCell><TableCell sx={{ fontWeight: 600 }}>日期时间</TableCell><TableCell sx={{ fontWeight: 600 }}>用户名</TableCell><TableCell sx={{ fontWeight: 600 }}>实验室</TableCell><TableCell sx={{ fontWeight: 600 }}>项目</TableCell><TableCell align="right" sx={{ fontWeight: 600 }}>数量</TableCell><TableCell sx={{ fontWeight: 600 }}>操作</TableCell></TableRow></TableHead><TableBody>{ul.length === 0 ? <TableRow><TableCell colSpan={7} align="center">暂无数据</TableCell></TableRow> : ul.map((r, i) => (<TableRow key={r.id} hover><TableCell>{(ulp - 1) * PS + i + 1}</TableCell><TableCell sx={{ whiteSpace: 'nowrap' }}>{r.recorded_at}</TableCell><TableCell>{r.user_name}</TableCell><TableCell>{r.group_name}</TableCell><TableCell>{r.project_name}</TableCell><TableCell align="right"><Chip label={r.quantity} size="small" sx={chipSx} /></TableCell><TableCell><IconButton size="small" onClick={() => oed(r)} title="编辑" sx={{ color: '#667eea' }}><EditIcon fontSize="small" /></IconButton><IconButton size="small" color="error" onClick={() => odu(r.user_name)} title="删除该用户所有记录"><DeleteForeverIcon fontSize="small" /></IconButton></TableCell></TableRow>))}</TableBody></Table></TableContainer>{ult > PS && (<Box sx={{ display: 'flex', justifyContent: 'center', mt: 2, gap: 1 }}><Button size="small" disabled={ulp <= 1} onClick={() => lul(ulp - 1)}>上一页</Button><Typography variant="body2" sx={{ alignSelf: 'center' }}>{ulp} / {Math.max(1, Math.ceil(ult / PS))}</Typography><Button size="small" disabled={ulp * PS >= ult} onClick={() => lul(ulp + 1)}>下一页</Button></Box>)}</>}</Box>)}
  </Box>}</Box>); };

  return (<Box><Typography variant="h5" fontWeight={700} sx={{ mb: 3, px: 1, background: 'linear-gradient(135deg, #00897b, #43a047)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>统计分析</Typography>{sm && <StatsCards summary={sm} onCardClick={x => { setAc(x); setEr(''); }} />}<Box sx={{ mb: 3, px: 1 }}><DateRangePicker startDate={s} endDate={e} onStartChange={setS} onEndChange={setE} /><Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 1 }}><Button variant="contained" startIcon={<DownloadIcon />} onClick={hx} size="small" sx={{ borderRadius: R, background: 'linear-gradient(135deg, #00897b, #43a047)', boxShadow: '0 4px 14px rgba(0,137,123,0.3)', '&:hover': { background: 'linear-gradient(135deg, #00796b, #388e3c)' } }}>导出 Excel</Button></Box></Box>{ac ? cct() : cg()}<Dialog open={edo} onClose={() => setEdo(false)} maxWidth="sm" fullWidth PaperProps={{ sx: { borderRadius: R } }}><DialogTitle sx={{ fontWeight: 700 }}>编辑记录</DialogTitle><DialogContent>{ee && <Alert severity="error" sx={{ mb: 2, borderRadius: R }}>{ee}</Alert>}<TextField label="用户名" fullWidth value={ef.user_name} onChange={x => setEf({ ...ef, user_name: x.target.value })} sx={{ mt: 1, '& .MuiOutlinedInput-root': { borderRadius: R } }} /><TextField label="数量" type="number" fullWidth value={ef.quantity} onChange={x => setEf({ ...ef, quantity: Number(x.target.value) })} sx={{ mt: 2, '& .MuiOutlinedInput-root': { borderRadius: R } }} inputProps={{ min: 1 }} /><TextField label="日期时间" type="datetime-local" fullWidth value={ef.recorded_at} onChange={x => setEf({ ...ef, recorded_at: x.target.value })} sx={{ mt: 2, '& .MuiOutlinedInput-root': { borderRadius: R } }} InputLabelProps={{ shrink: true }} /></DialogContent><DialogActions><Button onClick={() => setEdo(false)}>取消</Button><Button onClick={hes} variant="contained">保存</Button></DialogActions></Dialog><ConfirmDialog open={duo} title="删除用户记录" message={`确定要删除用户「${dun}」在所选日期范围内的所有记录吗？`} confirmText="删除" cancelText="取消" onConfirm={hdu} onCancel={() => setDuo(false)} /></Box>);
};
export default StatsPage;
